version: "3.8"

services:
  postgres:
    image: docker.iranserver.com/postgres:${POSTGRES_VERSION}
    container_name: safechat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - safechat

  synapse:
    image: docker.iranserver.com/matrixdotorg/synapse:${SYNAPSE_VERSION}
    container_name: safechat-synapse
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SERVER_IP: ${SERVER_IP}
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./synapse/data:/data
    networks:
      - safechat

  synapse-admin:
    image: docker.iranserver.com/awesometechnologies/synapse-admin:${SYNAPSE_ADMIN_VERSION}
    container_name: safechat-admin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - safechat

  ssh:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
      target: ssh
      network: host
    image: safechat-ssh:latest
    container_name: safechat-ssh
    restart: unless-stopped
    environment:
      TZ: Asia/Tehran
      SSH_PASSWORD: ${SSH_PASSWORD}
    ports:
      - "4949:22"
    networks:
      - safechat

networks:
  safechat:
    driver: bridge
    name: safechat
